services:
  db:
    # Pulled Apr 24, 2023
    image: postgres:15@sha256:6cc97262444f1c45171081bc5a1d4c28b883ea46a6e0d1a45a8eac4a7f4767ab
    environment:
      POSTGRES_PASSWORD: "123456"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=postgres"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 80s

  migrate:
    image: openlaw-archive-app
    build: .
    restart: on-failure
    environment: &commonenv
      DJANGO_SECRET_KEY: "#-@^btdzoe9n-swq=fx5(db5^ibkqsytrt0ie2n55efz7wtpk#"
      DEBUG: "True"
      DJANGO_DATABASE_ENGINE: "postgres"
      DJANGO_DATABASE_NAME: "postgres"
      DJANGO_DATABASE_USER: "postgres"
      DJANGO_DATABASE_PASSWORD: "123456"
      DJANGO_DATABASE_HOST: "db"
      DJANGO_DATABASE_PORT: "5432"
      DJANGO_ALLOWED_HOSTS: "*"
      DJANGO_CSRF_TRUSTED_ORIGINS: "http://localhost:8000"
    depends_on: &dependsondb
      db:
        condition: service_healthy
    command: ["migrate"]

  nginx:
    image: openlaw-archive-nginx
    build:
      context: .
      dockerfile: nginx.Dockerfile

  web:
    image: openlaw-archive-app
    build: .
    environment:
      <<: *commonenv
    depends_on: *dependsondb
    command: ["web"]

  ingress:
    # Pulled Apr 24, 2023
    image: nginx@sha256:63b44e8ddb83d5dd8020327c1f40436e37a6fffd3ef2498a6204df23be6e7e94
    volumes:
      - ./ingress-nginx-default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - nginx
      - web

#  qcluster:
#    image: open-pension-ng
#    build: .
#    environment:
#      <<: *commonenv
#      DJANGO_Q_CLUSTER_SETTINGS_JSON: '{"workers": 2}'
#    depends_on: *dependsondb
#    command: ["qcluster"]

volumes:
  pgdata:
