# Generated by Django 4.2 on 2023-05-01 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Law",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wiki_page_id", models.IntegerField(unique=True)),
                ("knesset_id", models.IntegerField(null=True, unique=True)),
                ("akn_id", models.IntegerField(null=True, unique=True)),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Revision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wiki_rev_id", models.IntegerField(unique=True)),
                ("akn_id", models.IntegerField(null=True, unique=True)),
                ("name", models.CharField(max_length=51)),
                ("effective_date_start", models.DateField(null=True)),
                ("effective_date_end", models.DateField(null=True)),
                (
                    "law",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="versions.law"
                    ),
                ),
            ],
        ),
    ]
