# Generated by Django 4.2 on 2023-05-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("versions", "0002_alter_law_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="revision",
            name="name",
            field=models.CharField(max_length=251),
        ),
    ]
