# Generated by Django 4.2 on 2023-05-22 18:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("versions", "0003_alter_revision_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="law",
            name="akn_id",
        ),
        migrations.RemoveField(
            model_name="law",
            name="knesset_id",
        ),
        migrations.RemoveField(
            model_name="revision",
            name="akn_id",
        ),
        migrations.RemoveField(
            model_name="revision",
            name="effective_date_end",
        ),
        migrations.AddField(
            model_name="revision",
            name="source_text",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
